

import type { Course } from './types';

export const coursesData: Course[] = [
  {
    id: '1',
    title: 'Go Programming - من البداية للاحتراف',
    titleArabic: 'برمجة Go - من البداية للاحتراف',
    titleEnglish: 'Go Programming - From Zero to Hero',
    titleSmall: 'تعلم لغة Go الحديثة وبناء تطبيقات عالية الأداء',
    instructor: 'علي الحسيني',
    category: 'البرمجة',
    price: 199,
    originalPrice: 499,
    image: '/go.jpeg',
    rating: 4.8,
    studentsCount: 8945,
    duration: '35 ساعة',
    level: 'مبتدئ',
    enrolledStudents: [
      { name: 'محمد علي', avatar: '/diverse-avatars.png' },
      { name: 'فاطمة أحمد', avatar: '/diverse-avatars.png' },
      { name: 'سارة خالد', avatar: '/diverse-avatars.png' },
    ],
    description: 'تعلم لغة Go من الصفر وإنشاء تطبيقات احترافية',
    startDate: '2024-03-15',
    whatYouLearn: [
      'أساسيات لغة Go والمتغيرات والأنواع',
      'البرمجة الموجهة للعمليات والبرمجة الوظيفية',
      'معالجة الأخطاء والمعالجات',
      'بناء تطبيقات ويب باستخدام Go',
      'إدارة قواعد البيانات',
      'نشر التطبيقات على الخوادم',
      'اختبار وتصحيح البرامج',
    ],
    requirements: ['معرفة أساسية بمبادئ البرمجة', 'حاسوب بمعالج وذاكرة عادية', 'رغبة في تعلم لغة برمجة جديدة'],
  },
  {
    id: '2',
    title: 'ROS - نظام التشغيل الروبوتي',
    titleArabic: 'ROS - نظام التشغيل الروبوتي',
    titleEnglish: 'ROS - Robot Operating System',
    titleSmall: 'نظام التشغيل المتخصص لتطوير الروبوتات الذكية',
    instructor: 'محمد الريس',
    category: 'الروبوتات',
    price: 349,
    originalPrice: 699,
    image: '/ros.png',
    rating: 4.7,
    studentsCount: 5623,
    duration: '50 ساعة',
    level: 'متقدم',
    enrolledStudents: [
      { name: 'أحمد محمود', avatar: '/diverse-avatars.png' },
      { name: 'ليلى إبراهيم', avatar: '/diverse-avatars.png' },
      { name: 'خالد حسن', avatar: '/diverse-avatars.png' },
    ],
    description: 'تعلم نظام التشغيل الروبوتي ROS وبناء روبوتات ذكية',
    startDate: '2024-04-01',
    whatYouLearn: [
      'أساسيات نظام ROS والعقد والموضوعات',
      'البرمجة باستخدام Python و C++ مع ROS',
      'التحكم بأجهزة الاستشعار والمحركات',
      'البرمجة الموزعة والاتصالات بين الأنظمة',
      'محاكاة الروبوتات في بيئة حقيقية',
      'بناء روبوتات متحركة وذكية',
    ],
    requirements: [
      'معرفة متقدمة بلغة البرمجة C++ أو Python',
      'فهم أساسي للروبوتات والأتمتة',
      'نظام Linux مثبت على الحاسوب',
    ],
  },
  {
    id: '3',
    title: 'أنظمة التحكم الآلي PLC',
    titleArabic: 'أنظمة التحكم الآلي PLC',
    titleEnglish: 'PLC Programmable Logic Controllers',
    titleSmall: 'تعلم برمجة وتشغيل أنظمة التحكم الآلي الصناعية',
    instructor: 'ياسر العتيبي',
    category: 'الأتمتة',
    price: 279,
    originalPrice: 599,
    image: '/plc.jpeg',
    rating: 4.6,
    studentsCount: 7234,
    duration: '45 ساعة',
    level: 'متوسط',
    enrolledStudents: [
      { name: 'عمر الشاطري', avatar: '/diverse-avatars.png' },
      { name: 'نور الدين', avatar: '/diverse-avatars.png' },
      { name: 'رائد علي', avatar: '/diverse-avatars.png' },
    ],
    description: 'دورة شاملة في أنظمة التحكم الآلي والبرمجة باستخدام PLC',
    startDate: '2024-03-20',
    whatYouLearn: [
      'مقدمة عن أنظمة التحكم الآلي والصناعة 4.0',
      'لغات البرمجة في PLC وتطبيقاتها',
      'تصميم وتطوير الدوائر المنطقية',
      'معالجة الإشارات والمدخلات والمخرجات',
      'تطبيقات صناعية حقيقية',
      'الصيانة والاختبار والتصحيح',
      'معايير السلامة في الأنظمة الصناعية',
    ],
    requirements: [
      'معرفة أساسية بالكهرباء والإلكترونيات',
      'فهم مبادئ المنطق الرقمي',
      'رغبة في العمل في المجال الصناعي',
    ],
  },
  {
    id: '4',
    title: 'دورة إتقان القرآن الكريم',
    titleArabic: 'دورة إتقان القرآن الكريم',
    titleEnglish: 'Quranic Recitation Mastery Course',
    titleSmall: 'تعلم تلاوة القرآن الكريم بالتجويد الصحيح من المتخصصين',
    instructor: 'أحمد محمد',
    category: 'القرآن الكريم',
    price: 299,
    originalPrice: 599,
    image: '/q.avif',
    rating: 4.9,
    studentsCount: 12458,
    duration: '40 ساعة',
    level: 'مبتدئ',
    enrolledStudents: [
      { name: 'محمد علي', avatar: '/diverse-avatars.png' },
      { name: 'فاطمة أحمد', avatar: '/diverse-avatars.png' },
      { name: 'سارة خالد', avatar: '/diverse-avatars.png' },
    ],
    description: 'دورة شاملة لتعلم تلاوة القرآن الكريم بالتجويد الصحيح',
    startDate: '2024-03-15',
    whatYouLearn: [
      'أحكام التجويد الأساسية والتطبيق العملي',
      'مخارج الحروف والصفات الصوتية',
      'أحكام النون والتنوين والميم الساكنة',
      'الوقف والسكت والمد الصحيح',
      'تعليم السور الصغرى والقصيرة',
      'تحسين النطق والتلاوة',
      'ختم القرآن الكريم بتدبر وفهم',
      'دروس في التفسير الميسر',
    ],
    requirements: ['عدم الحاجة إلى معرفة سابقة', 'جهاز للاستماع والمشاهدة', 'الرغبة في تعلم القرآن الكريم وحفظه'],
  },
  {
    id: '5',
    title: 'الروبوتات المتقدمة  ',
    titleArabic: 'الروبوتات المتقدمة  ',
    titleEnglish: 'Advanced Robotics   ',
    titleSmall: 'بناء روبوتات ذكية باستخدام أحدث تقنيات الذكاء الاصطناعي',
    instructor: 'دعيع الحربي',
    category: 'الروبوتات',
    price: 399,
    originalPrice: 799,
    image: '/robotics.jpeg',
    rating: 4.8,
    studentsCount: 6789,
    duration: '55 ساعة',
    level: 'متقدم',
    enrolledStudents: [
      { name: 'حسن محمود', avatar: '/diverse-avatars.png' },
      { name: 'مريم الدعيع', avatar: '/diverse-avatars.png' },
      { name: 'سلطان محمد', avatar: '/diverse-avatars.png' },
    ],
    description: 'تعلم بناء الروبوتات الذكية باستخدام الذكاء الاصطناعي والتعلم الآلي',
    startDate: '2024-04-10',
    whatYouLearn: [
      'أساسيات التعلم الآلي وشبكات العصبية',
      'الرؤية الحاسوبية والمعالجة الآلية للصور',
      'التحكم الآلي والملاحة للروبوتات',
      'معالجة اللغة الطبيعية والتفاعل الذكي',
      'بناء نماذج تنبؤية متقدمة',
      'تطبيقات الروبوتات في الصناعة والطب',
    ],
    requirements: [
      'معرفة متقدمة بلغة Python والمكتبات العلمية',
      'فهم عميق لمبادئ الذكاء الاصطناعي',
      'خبرة بالروبوتات والأنظمة المدمجة',
    ],
  },
  {
    id: '6',
    title: 'Python - دورة شاملة من الصفر للاحتراف',
    titleArabic: 'Python - دورة شاملة من الصفر للاحتراف',
    titleEnglish: 'Python - Complete Course from Zero to Pro',
    titleSmall: 'تعلم Python وبناء تطبيقات احترافية خطوة بخطوة',
    instructor: 'محمود أحمد',
    category: 'البرمجة',
    price: 249,
    originalPrice: 549,
    image: '/python.jpeg',
    rating: 4.9,
    studentsCount: 15678,
    duration: '48 ساعة',
    level: 'مبتدئ',
    enrolledStudents: [
      { name: 'علي حسن', avatar: '/diverse-avatars.png' },
      { name: 'نور محمد', avatar: '/diverse-avatars.png' },
      { name: 'لؤي الحارثي', avatar: '/diverse-avatars.png' },
    ],
    description: 'تعلم لغة Python من الصفر وإنشاء تطبيقات احترافية',
    startDate: '2024-03-18',
    whatYouLearn: [
      'أساسيات Python والمتغيرات والأنواع',
      'البنى الحلقية والشروط والدوال',
      'معالجة القوائم والقواميس والأوضاع الأخرى',
      'البرمجة الموجهة للكائنات OOP',
      'التعامل مع الملفات وقواعد البيانات',
    ],
    requirements: ['معرفة أساسية بمبادئ البرمجة', 'حاسوب بموارد متوسطة', 'رغبة في تعلم البرمجة واحترافها'],
  },
  {
    id: '7',
    title: 'دورة الصيدلي المحترف',
    titleArabic: 'دورة الصيدلي المحترف',
    titleEnglish: 'Professional Pharmacist Course',
    titleSmall: 'تطوير مهارات الصيدلي الحديث وإدارة الصيدليات بكفاءة',
    instructor: 'د. سارة الطياري',
    category: 'الصيدلة',
    price: 329,
    originalPrice: 699,
    image: '/pharmacie.jpeg',
    rating: 4.7,
    studentsCount: 4532,
    duration: '42 ساعة',
    level: 'متوسط',
    enrolledStudents: [
      { name: 'رغد الحربي', avatar: '/diverse-avatars.png' },
      { name: 'أروى العمري', avatar: '/diverse-avatars.png' },
      { name: 'ريم الدوسري', avatar: '/diverse-avatars.png' },
    ],
    description: 'دورة متقدمة في الصيدلة والأدوية وإدارة الصيدليات',
    startDate: '2024-04-05',
    whatYouLearn: [
      'الأدوية والمركبات الفعالة والتفاعلات الدوائية',
      'صرف الأدوية والاستشارات الصيدلانية',
      'إدارة المخزون والموارد في الصيدلية',
      'القوانين الصيدية والتشريعات الدوائية',
      'التثقيف الصحي للمرضى والعملاء',
      'معالجة الحالات الطبية الطارئة',
      'نظم المعلومات الصيدلية والحاسوب',
    ],
    requirements: [
      'حاصل على درجة البكالوريوس في الصيدلة',
      'معرفة بالمصطلحات الطبية والعلمية',
      'رغبة في تطوير المهارات الحديثة',
    ],
  },
  {
    id: '8',
    title: 'الذكاء الاصطناعي والتعلم الآلي',
    titleArabic: 'الذكاء الاصطناعي والتعلم الآلي',
    titleEnglish: 'Artificial Intelligence and Machine Learning',
    titleSmall: 'تعلم بناء نماذج الذكاء الاصطناعي والتنبؤ بالبيانات',
    instructor: 'د. فهد السلطان',
    category: 'الذكاء الاصطناعي',
    price: 429,
    originalPrice: 899,
    image: '/ia.jpeg',
    rating: 4.8,
    studentsCount: 9876,
    duration: '60 ساعة',
    level: 'متقدم',
    enrolledStudents: [
      { name: 'محمد الزهراني', avatar: '/diverse-avatars.png' },
      { name: 'جميلة الدعيع', avatar: '/diverse-avatars.png' },
      { name: 'أحمد العسكر', avatar: '/diverse-avatars.png' },
    ],
    description: 'تعلم أساسيات الذكاء الاصطناعي والتعلم الآلي وبناء نماذج ذكية',
    startDate: '2024-04-08',
    whatYouLearn: [
      'مقدمة عن الذكاء الاصطناعي والتعلم الآلي',
      'الخوارزميات الأساسية والتصنيف والتجميع',
      'شبكات العصب الاصطناعية والتعلم العميق',
      'معالجة البيانات والتحليل الإحصائي',
      'بناء نماذج تنبؤية دقيقة',
      'التطبيقات العملية في الأعمال والصناعة',
    ],
    requirements: [
      'معرفة قوية بلغة Python والرياضيات',
      'فهم الإحصائيات والاحتمالات',
      'خبرة بمكتبات ML مثل Scikit-learn و TensorFlow',
    ],
  },
  {
    id: '9',
    title: 'التصميم الجرافيكي الاحترافي',
    titleArabic: 'التصميم الجرافيكي الاحترافي',
    titleEnglish: 'Professional Graphic Design',
    titleSmall: 'إتقان فنون التصميم وإنشاء تصاميم احترافية تجارية',
    instructor: 'ليث الحربي',
    category: 'التصميم',
    price: 189,
    originalPrice: 449,
    image: '/figma.jpeg',
    rating: 4.6,
    studentsCount: 11245,
    duration: '38 ساعة',
    level: 'مبتدئ',
    enrolledStudents: [
      { name: 'زين الدين', avatar: '/diverse-avatars.png' },
      { name: 'منى حسن', avatar: '/diverse-avatars.png' },
      { name: 'علي محمود', avatar: '/diverse-avatars.png' },
    ],
    description: 'تعلم أساسيات التصميم الجرافيكي واستخدام أدوات التصميم الاحترافية',
    startDate: '2024-03-25',
    whatYouLearn: [
      'أساسيات التصميم والألوان والطباعة',
      'استخدام أدوات التصميم Adobe Creative Suite',
      'تصميم الشعارات والهويات البصرية',
      'تصميم المواد التسويقية والإعلانية',
      'تصميم الوسائط الرقمية والويب',
      'التصميم الجرافيكي للشبكات الاجتماعية',
      'مشاريع عملية وحقيقية',
    ],
    requirements: ['معرفة أساسية بأجهزة الحاسوب', 'حس فني وإبداعي عالي', 'توفر برامج التصميم الاحترافية'],
  },
  {
    id: '10',
    title: 'الإلكترونيات والدوائر الكهربائية',
    titleArabic: 'الإلكترونيات والدوائر الكهربائية',
    titleEnglish: 'Electronics and Electrical Circuits',
    titleSmall: 'تعلم الإلكترونيات وتصميم ومحاكاة الدوائر الكهربائية',
    instructor: 'محمود الغويني',
    category: 'الإلكترونيات',
    price: 269,
    originalPrice: 549,
    image: '/electronics.jpeg',
    rating: 4.7,
    studentsCount: 6543,
    duration: '44 ساعة',
    level: 'متوسط',
    enrolledStudents: [
      { name: 'عبدالله الحسن', avatar: '/diverse-avatars.png' },
      { name: 'فاطمة محمد', avatar: '/diverse-avatars.png' },
      { name: 'خالد العتيبي', avatar: '/diverse-avatars.png' },
    ],
    description: 'دورة شاملة في الإلكترونيات والدوائر الكهربائية والمشاريع العملية',
    startDate: '2024-04-02',
    whatYouLearn: [
      'أساسيات الكهرباء والتيار والجهد والمقاومة',
      'المكونات الإلكترونية والترانزستورات',
      'الدوائر المتكاملة والمنطقية',
      'محاكاة الدوائر باستخدام برامج متخصصة',
      'تصميم ولحام الدوائر المطبوعة PCB',
      'مشاريع إلكترونية عملية',
      'الأمان والمعايير في الأعمال الكهربائية',
      'تطبيقات صناعية وعملية',
    ],
    requirements: [
      'معرفة أساسية بالفيزياء والرياضيات',
      'فهم المفاهيم الكهربائية الأساسية',
      'رغبة في العمل بمشاريع عملية',
    ],
  },
];

export const categories = ['الكل', 'القرآن الكريم', 'coding'];

export const priceRanges = [
  { label: 'الكل', value: 'all' },
  { label: 'أقل من 5 ساعات', value: '0-5' },
  { label: '5-10 ساعات', value: '5-10' },
  { label: 'أكثر من 10 ساعات', value: '10+' },
];

export const levels = [
  { label: 'الكل', value: 'all' },
  { label: 'مبتدئ', value: 'مبتدئ' },
  { label: 'متوسط', value: 'متوسط' },
  { label: 'متقدم', value: 'متقدم' },
];

export const certificateTypes = [
  { label: 'الكل', value: 'all' },
  { label: 'شهادة معتمدة', value: 'certified' },
  { label: 'شهادة مشاركة', value: 'participation' },
];
